### PR TITLE
Improve write performance

### PR DESCRIPTION
**Pull request by BridgeAR**
See https://github.com/nodejs/node/pull/19289. I did not run dedicated benchmarks here.

### CODE REVIEW

**Comment by mscdex** [comment]
Did you check previous node branches to see how this change affects them (positively or negatively)?

**Comment by BridgeAR** [comment]
I ran those from Node.js 6 > 10-pre and either the performance is identical or better.

**Comment by BridgeAR** [comment]
4 is identical as well.

**Comment by mscdex** [comment]
I just tested these on each branch (including master) and my version of these functions, without the validation code, perform exactly the same as the previous implementations. Here's what I used to benchmark:

```js
const n = 1e9;
const b = Buffer.alloc(4);

function writeUInt32BE(buf, value, offset) {
  buf[offset++] = (value >>> 24);
  buf[offset++] = (value >>> 16);
  buf[offset++] = (value >>> 8);
  buf[offset++] = value;
  return offset;
}
console.time('original');
for (var i = 0; i < n; ++i)
  writeUInt32BE(b, 0xffff, 0);
console.timeEnd('original');

/*
function writeUInt32BE(buf, value, offset) {
  buf[offset + 3] = value;
  value = value >>> 8;
  buf[offset + 2] = value;
  value = value >>> 8;
  buf[offset + 1] = value;
  value = value >>> 8;
  buf[offset] = value;
  return offset + 4;
}
console.time('new');
for (var i = 0; i < n; ++i)
  writeUInt32BE(b, 0xffff, 0);
console.timeEnd('new');
*/
```

Just comment out one and uncomment the other and compare. For me, I get ~1033ms.

**Comment by BridgeAR** [comment]
To me it looks like the code is going to be inlined and this does not benchmark what should be benchmarked. Changing `0xffff` to a number that is increased with each call should prevent this and yield a clearer result.

**Comment by mscdex** [comment]
Ok I modified the loop to:

```js
  if (i % 2 === 0)
    writeUInt32BE(b, 0xffff, 0);
  else
    writeUInt32BE(b, 0xff, 0);
```

and now on node master, the original implementation (~3480ms) is faster than this PR (~3520ms).

Also there is a strange performance issue starting with node v9 where it takes over twice as long as previous node branches. Node v8 and older take only ~1400-1500ms for either implementation.

**Comment by BridgeAR** [comment]
Ok, I ran a couple of different benchmarks again and it somewhat seems to depend on the input size what function is faster. Since there is no ideal solution, I am going to close this.

**Pull request closed without merging**
