### PR TITLE
test: fix failing unit tests due to assert in exit event handler

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by mscdex** [comment]
This is not a solution as this just hides an underlying issue with node (v10.0.0 to be exact) upstream.

**Comment by DanielRuf** [comment]
To be honest, it is unclear to my why this should be a bug in Node 10 (is there some issue about this?) and the assert in there makes not much sense to me. I feel like this is intended and deprecated / due to internal changes which should work like this.

**Comment by mscdex** [comment]
The issue is that an arguably semver-major change was made to node only a few days before v10.0.0 was released and that is causing the tests to fail as-is. The assert is necessary because all tests should complete when the process exits. If not all of them did, then something went wrong and it'd be nice to be able to know that.

**Comment by DanielRuf** [comment]
> The assert is necessary because all tests should complete when the process exits

Huh? No this check does not do this. It also outputs `Only finished 0/5 tests` at the moment. `assert` just compares the alues in the condition (to be equal), just like normal `assert.equals` works in unit testing in general.

**Comment by mscdex** [comment]
> No this check does not do this.

Trust me, it does. `t` is only incremented via `next()` after each test finishes. So if when the process exits and `t !== tests.length`, then obviously something is very wrong.


> It also outputs Only finished 0/5 tests at the moment

Yes, but only on node v10.0.0 and for the reason I previously mentioned.

**Pull request closed without merging**
