### PR TITLE
Pull requests for Fixing host key algorithm selection, Adding support for configuring multiple host private keys and Fixing parseKey for parsing OPENSSH public keys.

### PR DESCRIPTION
**Pull request by nrjpoddar**

### CODE REVIEW

**Comment by mscdex** [comment]
Some quick comments after briefly looking over things:

* These commits should be split up into separate PRs as they are unrelated to each other

* For allowing multiple (host) private keys, I think it'd be simpler to instead allow arrays of Buffers/strings instead of an object keyed on key algorithm. If the array contains duplicate key algorithms, just take the first key of that algorithm.

* Some tests are needed for the multiple private key feature and the host key algorithm selection

**Comment by nrjpoddar** [comment]
Thanks Brian for the quick feedback.

   - I will split them up into separate PRs. I wasn't sure which way was
   easier for you.
   - I think having an Object with keys corresponding to algorithm names
   makes it very clear to user how they are supposed to configure the private
   keys and also makes it easier for them to reason about which key will be
   used for an algorithm. I implemented the code in a way old behavior is
   preserved. I agree your suggestion might be simpler but it's more confusing
   to a user.
   - I will try and add some tests and submit a PR.


On Wed, May 20, 2015 at 3:28 PM, Brian White <notifications@github.com>
wrote:

> Some quick comments after briefly looking over things:
>
>    -
>
>    These commits should be split up into separate PRs as they are
>    unrelated to each other
>    -
>
>    For allowing multiple (host) private keys, I think it'd be simpler to
>    instead allow arrays of Buffers/strings instead of an object keyed on key
>    algorithm. If the array contains duplicate key algorithms, just take the
>    first key of that algorithm.
>    -
>
>    Some tests are needed for the multiple private key feature and the
>    host key algorithm selection
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mscdex/ssh2-streams/pull/14#issuecomment-104044451>.
>



-- 
Regards,
Neeraj Poddar
Software Engineer
F5 Networks

**Comment by mscdex** [comment]
The natural order in which the private keys are in the array would dictate what keys/algorithms get used first, second, etc. Technically you can't rely on the ordering of properties on an object though, it just so happens that V8 *currently* keeps them in the same order they are defined in.

The other benefit to using the array is that the user does not have to know in advance the key's algorithm. If they did not know the algorithm in advance (e.g. spinning up a server with a variable/arbitrary key file supplied by the user), the key would have to be parsed twice.

**Comment by mscdex** [comment]
Additionally, this is somewhat unrelated, but it would be nice to also allow multiple private keys for the client as well (but this could be added separately from the PR for host keys).

**Comment by nrjpoddar** [comment]
With this approach there are few more issues. Firstly, RFC states that for
host key algorithm selection both sides should walk down *client's* list
and pick the first one that's supported in both, so order of things sent by
server is not important.

Secondly, we have to specify a way for users to configure passphrases if
required by private keys. With my current implementation I allow the
existing method and also allow users to configure an Object for passphrase
with same property names as private keys. If your approach is followed,
then passphrases cannot be entered as a separate entity (as there is no
mapping between private keys and passphrases). Passphrases have to be tied
to the private key making it an Object like this :-

[
  { key1 , passphrase1},
  {key2 },
  {key3, passphrase3}
]

To preserve the old behavior you will now have two separate methods of
entering passphrases which is even more confusing.

On Wed, May 20, 2015 at 6:43 PM, Brian White <notifications@github.com>
wrote:

> The natural order in which the private keys are in the array would dictate
> what keys/algorithms get used first, second, etc. Technically you can't
> rely on the ordering of properties on an object though, it just so happens
> that V8 *currently* keeps them in the same order they are defined in.
>
> The other benefit to using the array is that the user does not have to
> know in advance the key's algorithm. If they did not know the algorithm in
> advance (e.g. spinning up a server with a variable/arbitrary key file
> supplied by the user), the key would have to be parsed twice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mscdex/ssh2-streams/pull/14#issuecomment-104082487>.
>



-- 
Regards,
Neeraj Poddar
Software Engineer
F5 Networks

**Comment by mscdex** [comment]
My suggestion would be if `config.privateKey` is an array, then `config.passphrase` is ignored.

For encrypted keys in the array, such elements would look like `{ privateKey: ...., passphrase: .... }` and for unencrypted keys, such elements could simply be Buffers/strings and/or maybe `{ privateKey: ... }`.

**Comment by nrjpoddar** [comment]
Ok. I might take some time to allow configuration in the new format and for
writing unit tests. I will split up my commits and submit PRs for other bug
fixes.

On Thu, May 21, 2015 at 12:58 PM, Brian White <notifications@github.com>
wrote:

> My suggestion would be if config.privateKey is an array, then
> config.passphrase is ignored.
>
> For encrypted keys in the array, such elements would look like {
> privateKey: ...., passphrase: .... } and for unencrypted keys, such
> elements could simply be Buffers/strings and/or maybe { privateKey: ... }.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mscdex/ssh2-streams/pull/14#issuecomment-104388803>.
>



-- 
Regards,
Neeraj Poddar
Software Engineer
F5 Networks

**Comment by nrjpoddar** [comment]
Can you explain what exactly you need for client Private Key in
ssh2-streams? Is it for UserAuth or Agent forwarding?

On Wed, May 20, 2015 at 6:46 PM, Brian White <notifications@github.com>
wrote:

> Additionally, this is somewhat unrelated, but it would be nice to also
> allow multiple private keys for the client as well (but this could be added
> separately from the PR for host keys).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mscdex/ssh2-streams/pull/14#issuecomment-104082723>.
>



-- 
Regards,
Neeraj Poddar
Software Engineer
F5 Networks

**Comment by mscdex** [comment]
Private keys are also used for user authentication.

**Comment by mscdex** [comment]
I recently committed multiple host key support in master, but with some differences:

* There is no more host key parsing in `SSH2Stream`, this was done as an optimization (no re-parsing host keys for every client connection). Implementors must now supply an object (keyed on format name) containing decrypted keys.

* The server host key format list sent to clients is not automatically calculated from the host keys (again, as an optimization). Implementors must pass correct formats that match the host keys used (this is part of a larger support for custom algorithms/formats used during handshaking).

As far as the key parsing change goes, if I understand what it's doing correctly (allowing comments immediately after key data without spaces), I don't think that is something that is desired. Even `ssh-keygen` rejects such keys when it tries to parse them. If your key parser change was designed to do something other than this, let me know.

**Pull request closed without merging**
