### PR TITLE
chore: reformat package.json

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by mscdex** [comment]
I don't really see this as necessary. Thanks for the PR though.

**Comment by DanielRuf** [comment]
Well, everyone who runs `npm i` automatically gets this reformatted and the file appears as modified because of this so this makes sense imho.

**Comment by mscdex** [comment]
That seems more like more of an npm issue to me.

**Comment by mscdex** [comment]
I understand it does this automatically. What I'm saying is that to me, npm should not be modifying package.json implicitly. If you do `npm install foo --save`, then sure, it's expected that your own local package.json gets modified because you asked for it. However, just doing `npm install foo` I would *not* expect npm to touch my package.json.

**Comment by DanielRuf** [comment]
Sure but this still affects all contributors cloning the repo and working on it. I just ran `git clone` + `npm i` and got these changes so others will probably commit and push this too (by accident).

**Pull request closed without merging**
